repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.2  # Replace with latest tag
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format
        types_or: [python, pyi]
  - repo: local
    hooks:
      - id: nox
        name: nox
        entry: uvx nox
        language: python
        'types': [file]
        args: []
        require_serial: false
        additional_dependencies: []
        minimum_pre_commit_version: '0'
        pass_filenames: false
        stages: [pre-commit, pre-push]
