[project]
name = "template-cli-python"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer-slim[standard]>=0.16.0",
]

[project.scripts]
typer1 = "template_cli_python.cli:main_cli"

[tool.hatch.build.targets.wheel]
packages = [ "src" ]
